### ISSUE TITLE
Generate slug when importing

### ISSUE THREAD

**Issue by codebyray** [jeroenzwart/laravel-csv-seeder#17]
Hello,

Is there a way to set the slug from particular fields when importing a csv file?

Example would be:
```
name,address,city,state,postal
Bob,12345 This Rd,My City,NY,55555
```
I would like to generate a slug form: name,city,state,postal

I am currently using cviebrock/eloquent-sluggable to generate slugs, which is automated when adding a person to the database. However, when importing slugs are not created.

I see it is possible to set a default for a given column, I have this added to my seeder, which works partially:
```php
$this->defaults = [
    'slug' => SlugService::createSlug(Salon::class, 'slug',  'name')
];
```
All this does is put: name as the slug, how can I get the name,city,state,postal values when importing to update the slug?

Thank you in advance for any assistance.

**Comment by jeroenzwart** [comment]
Hi,
With defaults is it only possible to fill a column with a default value for every row. I made some changes and add a parser in v1.4 (#18) . So now you can do this;
`$this->parsers = ['slug' => function ($value) { 
            return SlugService::createSlug(Salon::class, 'slug', $value);
 }];`
