### ISSUE TITLE
Validation Rules

### ISSUE THREAD

**Issue by mskenderian** [jeroenzwart/laravel-csv-seeder#2]
Is there a way to set validation rules using laravel validator?

$this->mapping = ['id', 'zip_code', 'city'];
$this->validation_rules = [
            'zip_code' => 'required|unique:zip_codes|min:5|max:5',
            'city' => 'required|max:200',
        ];

**Comment by jeroenzwart** [comment]
No, but good idea. I will see if feature can be added.

**Comment by jeroenzwart** [comment]
See https://github.com/jeroenzwart/laravel-csv-seeder/releases/tag/v1.2
