### ISSUE TITLE
Error: Call to a member function line() on null

### ISSUE THREAD

**Issue by moetanahy** [jeroenzwart/laravel-csv-seeder#21]
Hi,

I'm trying to run a CSV seeder using the package, but having an error being thrown when seeding via a TestCase.

The error I'm getting is:
```
Error: Call to a member function line() on null
   │
   ╵ /Users/me/Workspaces/php/project/vendor/jeroenzwart/laravel-csv-seeder/src/CsvSeeder.php:458
   ╵ /Users/me/Workspaces/php/project/vendor/jeroenzwart/laravel-csv-seeder/src/CsvSeeder.php:403
   ╵ /Users/me/Workspaces/php/project/vendor/jeroenzwart/laravel-csv-seeder/src/CsvSeeder.php:381
   ╵ /Users/me/Workspaces/php/project/vendor/jeroenzwart/laravel-csv-seeder/src/CsvSeeder.php:262
   ╵ /Users/me/Workspaces/php/project/vendor/jeroenzwart/laravel-csv-seeder/src/CsvSeeder.php:185
   ╵ /Users/me/Workspaces/php/project/Modules/Database/Seeders/Lookups/MyTableSeeder.php:44
   ╵ /Users/me/Workspaces/php/project/vendor/laravel/framework/src/Illuminate/Database/Seeder.php:150
   ╵ /Users/me/Workspaces/php/project/vendor/laravel/framework/src/Illuminate/Database/Seeder.php:49
```
This is happening in my test case which I've tried two ways of running.
```
app(DatabaseSeeder::class)->call(MyTableSeeder::class);
```
This causes the error thrown above.

When running it using 
```
$this->seed(LedgerAccountTypeTableSeeder::class);
```
I get no error, but the test method is not actually completing and not executing any lines of code after the call to $this->seed

Any ideas what might be the problem?

**Comment by jeroenzwart** [comment]
Yes, the CsvSeeder extends the Seeder from Laravel. In both seeder classes there are given messages back to the console, if you call the seeder by cli. You should look for an example how to make a test with the Laravel Seeder. The difference will be not very big. Or maybe mock \Illuminate\Console\Command, which handles the outputs to the console.

**Comment by moetanahy** [comment]
Thanks - I did follow the instructions by Laravel at https://laravel.com/docs/8.x/database-testing#running-seeders - so was running it using $this->seed which should get this working (I've also got RefreshDatabase on as well).

Does this mean I should be mocking this within the call to the seeder to get this to work within a TestCase?  I'm not having this problem with the normal seeders - just my seeder inheriting from CsvSeeder

**Comment by jeroenzwart** [comment]
Can you try to change something in the CsvSeeder class?
Add the following if statement as first in the console() method;
`    private function console( $message, $level = FALSE )
    {
        if (isset($this->command) === FALSE) {
            return;
        }`
It should fix the error message, but this message is reason of a catch of the real error. The real error is trying to insert some rows into a table. The reason can be, for example there is no connection to the database or the table doesn't exists.
