### ISSUE TITLE
Found only one column in header, maybe a wrong delimiter (;) for the CSV file was set

### ISSUE THREAD

**Issue by mzcoder-hub** [jeroenzwart/laravel-csv-seeder#28]
Found only one column in header, maybe a wrong delimiter (;) for the CSV file was set

why ?

**Comment by jeroenzwart** [comment]
The table, where to import data into, has only one column?

**Comment by mzcoder-hub** [comment]
> The table, where to import data into, has only one column?

No it has 4 column, but now its fixed because i use

`$delimiter = ','`

Is the delimiter is required?

**Comment by jeroenzwart** [comment]
No, but delimiter has a default as ;
