### ISSUE TITLE
Auto incrementing id

### ISSUE THREAD

**Issue by shaneparsons** [jeroenzwart/laravel-csv-seeder#5]
Is there a way to have the `id` column of the table be auto incremented rather than having to map to an `id` column in the csv?

**Comment by shaneparsons** [comment]
Nevermind, it seems like it already works by default.

**Comment by jeroenzwart** [comment]
Skip the id column in your csv and set auto incremented in your table is a better way.

**Comment by shaneparsons** [comment]
Yeah, that's what I ended up doing. Cheers!
