### ISSUE TITLE
Encoding

### ISSUE THREAD

**Issue by TheGeremy** [jeroenzwart/laravel-csv-seeder#6]
Hi, i have csv files encoded in UTF8 and database fields are also UTF8, but the text is not the same as in the csv file. It looks like that your script will not read all characters correcly. Which encoding should the csv file be? For example sting "bežný člen" is read as "beÅ¾nÃ½ Älen". Thanks.

**Comment by TheGeremy** [comment]
I find out, when you do utf8_encode on already UTF8 string but with special characters like č, š, .... it will change those to some bullshit :D, so I change your code in CsvRowParser  >> ParseRow >> foreach to this:
            if(mb_detect_encoding($this->value) != 'UTF-8') {
                $this->doEncode();    
            }

**Comment by IsaacMujica** [comment]
Hello, to colaborate to this issue I suggest add a few lines:

* In CsvSeeder.php:

- Add the public property $encode:

    /**
     * If you want tu UTF-8 encode set TRUE
     * Default: TRUE
     * 
     * @var bollean
     */
    public $encode = TRUE;

- In the Method parseCSV pass the argument encode to CsvRowParser class:

        $parser = new CsvRowParser( $this->header, $this->defaults, $this->timestamps, $this->hashable, $this->validate, $this->encode );

* In CsvRowParser.php:

- Add the private property $encode:

    private $encode;

- Add the argument in the construct method:

    public function __construct( $header, $defaults, $timestamps, $hashable, $validate, $encode )

- Add the encode validate in the method doEncode:

    private function doEncode()
    {
        if($this->encode) if( is_string($this->value) ) $this->value = utf8_encode( $this->value );
    }

And does it!
Sorry for my english I hope this can help to anyone.

**Comment by TheGeremy** [comment]
I kindly thank you for this help. Do not be bothered by your english, that is not important. All done and submited. :)

**Comment by IsaacMujica** [comment]
I'm glad that I could help you Geremy :D

**Comment by jeroenzwart** [comment]
I had not so much time the last weeks, but your commit has been merged. Thanks to both
